### ISSUE TITLE
Homework assignments

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/SURI#1]
https://github.com/CU-ADCL/SURI/blob/bb2a865416b265fa973b198d788b47e15cc703b9/RunCode.md?plain=1#L79

We probably shouldn't mention homework assignments :)

**Comment by WhiffleFish** [comment]
Fixed in [5e36217](https://github.com/CU-ADCL/SURI/commit/5e362171264cbfe7426468ab3befaf2f3522f3f4)
