### ISSUE TITLE
Paragraphs

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/SURI#2]
https://github.com/CU-ADCL/SURI/blob/bb2a865416b265fa973b198d788b47e15cc703b9/RunCode.md?plain=1#L48

For some reason, the markdown processor is treating different lines as different paragraphs throughout the website. That seems to go against the official markdown specification, so I am not sure why it is doing that. But it makes all of the paragraphs have very rough right edges.

**Comment by WhiffleFish** [comment]
Should be fixed in 6fdc04b0f0320777ceefea78c4e5e131c16da18a
