### ISSUE TITLE
Catelog maintenance

### ISSUE THREAD

**Issue by zsunberg** [CU-ADCL/SURI#4]
https://github.com/CU-ADCL/SURI/blob/beb95e2c3e9e32d1052e90642a84aa93c62d6e13/_includes/research.md?plain=1#L18

@WhiffleFish In the ILP section, I think that we should mention that the goal is "Catalog Maintenance"

**Comment by WhiffleFish** [comment]
fixed in 5aef0bb78c4c673a74fb7898432186f4d771017e
